import type { SiteLanguage } from "@/contexts/LanguageContext";

export const homeCopy = {
  en: {
    menuBridge: "Explore the full menu",
    lateTable: "Mall Road’s late table",
    tableEyebrow: "02 / The Mall table · #FREEZETHEHAPPINESS",
    saveRoom: "Save room.",
    forScoop: "For the scoop.",
    scoopCopy: "From South Indian favourites and shareable pizza to Chinese, comfort snacks, shakes and dessert—Naatures Scuup keeps every vegetarian craving at one Mall Road table.",
    vegetarianDining: "Vegetarian multi-cuisine",
    cravingChapters: "17 craving chapters",
    exploreIceCreams: "Explore ice creams",
    directions: "Directions to Mall Road",
    beforeVisit: "04 / Before you visit",
    goodToKnow: "Good to",
    know: "know.",
    faqIntro: "Questions about a visit? Call ",
    faqEnding: ". We aim to respond within the current service window.",
    where: "Where is Naatures Scuup?",
    whereAnswer: "Find us at 126, The Mall Road, Mirpur, Kanpur, Uttar Pradesh 208004.",
    vegetarian: "Is the menu vegetarian?",
    vegetarianAnswer: "Yes. The restaurant presents a vegetarian multi-cuisine menu.",
    browse: "What can I browse online?",
    browseAnswer: "The digital menu lists 204 dishes across 17 groups, with search and price sorting.",
    order: "Can I order or reserve from this website?",
    orderAnswer: "For reservations or order enquiries, please call the restaurant directly.",
    directionsQuestion: "How do I get directions?",
    directionsAnswer: "Use the directions link above or the sticky mobile directions control to open Google Maps.",
  },
  hi: {
    menuBridge: "पूरा मेनू देखें",
    lateTable: "मॉल रोड की शाम वाली टेबल",
    tableEyebrow: "02 / मॉल रोड टेबल · #FREEZETHEHAPPINESS",
    saveRoom: "थोड़ी जगह",
    forScoop: "स्कूप के लिए।",
    scoopCopy: "साउथ इंडियन फेवरेट्स और शेयर करने लायक पिज़्ज़ा से लेकर चाइनीज़, कम्फर्ट स्नैक्स, शेक्स और डेज़र्ट तक—नेचर्स स्कूप हर शाकाहारी क्रेविंग को मॉल रोड की एक टेबल पर लाता है।",
    vegetarianDining: "शाकाहारी मल्टी-कुज़ीन",
    cravingChapters: "17 स्वाद अध्याय",
    exploreIceCreams: "आइसक्रीम देखें",
    directions: "मॉल रोड के निर्देश",
    beforeVisit: "04 / आने से पहले",
    goodToKnow: "जानना",
    know: "अच्छा है।",
    faqIntro: "आने से पहले कोई सवाल है? कॉल करें ",
    faqEnding: "। हम सेवा समय के भीतर जवाब देने की कोशिश करते हैं।",
    where: "नेचर्स स्कूप कहाँ है?",
    whereAnswer: "हमारा पता है: 126, द मॉल रोड, मिरपुर, कानपुर, उत्तर प्रदेश 208004।",
    vegetarian: "क्या मेनू शाकाहारी है?",
    vegetarianAnswer: "हाँ। रेस्टोरेंट में शाकाहारी मल्टी-कुज़ीन मेनू उपलब्ध है।",
    browse: "मैं ऑनलाइन क्या देख सकता/सकती हूँ?",
    browseAnswer: "डिजिटल मेनू में 17 ग्रुप्स में 204 डिश हैं, जिनमें सर्च और कीमत के अनुसार सॉर्ट करने की सुविधा है।",
    order: "क्या मैं इस वेबसाइट से ऑर्डर या रिज़र्व कर सकता/सकती हूँ?",
    orderAnswer: "रिज़र्वेशन या ऑर्डर संबंधी जानकारी के लिए कृपया सीधे रेस्टोरेंट को कॉल करें।",
    directionsQuestion: "मुझे दिशा-निर्देश कैसे मिलेंगे?",
    directionsAnswer: "Google Maps खोलने के लिए ऊपर दिए गए निर्देश लिंक या मोबाइल दिशानिर्देश नियंत्रण का उपयोग करें।",
  },
} as const;

export const dragCopy = {
  en: {
    dogLabel: "Greet the Naatures Scuup café dog",
    eyebrow: "01 / The food edit",
    titleStart: "Drag into",
    titleEnd: "the good bits.",
    body: "A small stack of real table moments from Naatures Scuup. Pull a card aside to find the next craving.",
    dragMe: "Drag me",
    swipeGuide: "Swipe a card in any direction",
    stackLabel: "A stack of Naatures Scuup food photographs. Drag in any direction, or use the arrow keys to reveal another food moment.",
    showing: "Showing item",
    of: "of",
    previous: "Show previous food moment",
    next: "Show next food moment",
  },
  hi: {
    dogLabel: "नेचर्स स्कूप कैफ़े डॉग को नमस्ते कहें",
    eyebrow: "01 / फूड एडिट",
    titleStart: "खींचें",
    titleEnd: "स्वादिष्ट पल।",
    body: "नेचर्स स्कूप की असली टेबल यादों का छोटा स्टैक। अगली क्रेविंग देखने के लिए एक कार्ड को किनारे खींचें।",
    dragMe: "खींचें",
    swipeGuide: "कार्ड को किसी भी दिशा में स्वाइप करें",
    stackLabel: "नेचर्स स्कूप के फूड फ़ोटो का स्टैक। किसी भी दिशा में खींचें या दूसरा फूड मोमेंट देखने के लिए ऐरो कीज़ का उपयोग करें।",
    showing: "आइटम",
    of: "में से",
    previous: "पिछला फूड मोमेंट दिखाएँ",
    next: "अगला फूड मोमेंट दिखाएँ",
  },
} as const;

export const menuCopy = {
  en: {
    current: "Full menu",
    atlas: "A vegetarian craving atlas",
    vegetarianMenu: "100% vegetarian menu",
    headlineStart: "Many cravings.",
    headlineEnd: "One table.",
    heroCopy: "From a hot dosa to a chilled scoop, move through every Mall Road mood in one craving atlas—made for reading, sharing and planning the next table.",
    chapterHours: "17 chapters · 204 dishes · Mon, Tue, Thu–Sun 11 AM–11 PM · Wed 10 AM–11 PM",
    browseChapters: "Browse Full Menu chapters",
    browseMenu: "Browse the Naatures Scuup menu",
    chapterNavigation: "Menu chapter navigation",
    previousChapters: "Show previous menu chapters",
    nextChapters: "Show next menu chapters",
    dragChapters: "Drag to browse menu chapters",
    searchPlaceholder: "Search dosa, pizza, ice cream, shakes…",
    searchDishes: "Search dishes",
    sortBy: "Sort by",
    sortItems: "Sort menu items",
    recommended: "Recommended",
    alphabetical: "A–Z",
    lowToHigh: "Price: low to high",
    highToLow: "Price: high to low",
    dishesToExplore: "dishes to explore",
    allCravings: "All cravings",
    noCraving: "No craving found",
    emptyStart: "Try another",
    emptyEnd: "table mood.",
    emptyCopy: "Search by a dish name, flavour or menu group. Your menu is still here—just waiting for a different word.",
    chapter: "Chapter",
    cravingChapter: "Craving chapter",
    firstPlate: "The first plate",
    pureVeg: "100% pure veg",
    menuPrice: "Menu price",
    priceNotListed: "Price not listed",
    menuListing: "Menu listing",
    closingEyebrow: "Freeze the happiness",
    closingStart: "Find your",
    closingEnd: "table mood.",
    getDirections: "Get directions",
    backHome: "Back to home",
  },
  hi: {
    current: "पूरा मेनू",
    atlas: "शाकाहारी क्रेविंग एटलस",
    vegetarianMenu: "100% शाकाहारी मेनू",
    headlineStart: "बहुत-सी क्रेविंग्स।",
    headlineEnd: "एक टेबल।",
    heroCopy: "गरम डोसा से लेकर ठंडे स्कूप तक, एक ही क्रेविंग एटलस में मॉल रोड के हर मूड को देखें—पढ़ने, शेयर करने और अगली टेबल प्लान करने के लिए।",
    chapterHours: "17 अध्याय · 204 डिश · सोम, मंगल, गुरु–रवि 11 AM–11 PM · बुध 10 AM–11 PM",
    browseChapters: "पूरा मेनू अध्याय देखें",
    browseMenu: "नेचर्स स्कूप मेनू देखें",
    chapterNavigation: "मेनू अध्याय नेविगेशन",
    previousChapters: "पिछले मेनू अध्याय दिखाएँ",
    nextChapters: "अगले मेनू अध्याय दिखाएँ",
    dragChapters: "मेनू अध्याय देखने के लिए खींचें",
    searchPlaceholder: "डोसा, पिज़्ज़ा, आइसक्रीम, शेक्स खोजें…",
    searchDishes: "डिश खोजें",
    sortBy: "इस अनुसार क्रम",
    sortItems: "मेनू आइटम क्रमबद्ध करें",
    recommended: "सुझाए गए",
    alphabetical: "A–Z",
    lowToHigh: "कीमत: कम से ज़्यादा",
    highToLow: "कीमत: ज़्यादा से कम",
    dishesToExplore: "डिश देखने के लिए",
    allCravings: "सभी क्रेविंग्स",
    noCraving: "कोई क्रेविंग नहीं मिली",
    emptyStart: "कोई दूसरा",
    emptyEnd: "मूड आज़माएँ।",
    emptyCopy: "डिश नाम, फ्लेवर या मेनू ग्रुप से खोजें। आपका मेनू यहीं है—बस एक दूसरे शब्द का इंतज़ार है।",
    chapter: "अध्याय",
    cravingChapter: "क्रेविंग अध्याय",
    firstPlate: "पहली प्लेट",
    pureVeg: "100% शुद्ध शाकाहारी",
    menuPrice: "मेनू कीमत",
    priceNotListed: "कीमत उपलब्ध नहीं",
    menuListing: "मेनू लिस्टिंग",
    closingEyebrow: "खुशी को ठंडा रखें",
    closingStart: "अपना",
    closingEnd: "टेबल मूड पाएँ।",
    getDirections: "दिशा-निर्देश",
    backHome: "होम पर वापस",
  },
} as const;

const hindiChapterTitles: Record<string, string> = {
  all: "सभी आइटम",
  starters: "स्टार्टर्स",
  "soups-salads": "सूप & सलाद",
  "main-course": "मेन कोर्स",
  breads: "ब्रेड्स",
  "rice-biryani": "राइस & बिरयानी",
  "south-indian": "साउथ इंडियन",
  chinese: "चाइनीज़",
  "fried-rice-noodles": "फ्राइड राइस & नूडल्स",
  "pizza-pasta": "पिज़्ज़ा & पास्ता",
  "burgers-sandwiches": "बर्गर्स & सैंडविचेस",
  snacks: "स्नैक्स",
  rolls: "रोल्स",
  maggi: "मैगी",
  accompaniments: "साथ में",
  "ice-creams": "आइसक्रीम",
  drinks: "ड्रिंक्स & शेक्स",
  "bakery-specials": "बेकरी स्पेशल्स",
};

export function localizeChapterTitle(slug: string, englishTitle: string, language: SiteLanguage) {
  return language === "hi" ? (hindiChapterTitles[slug] ?? englishTitle) : englishTitle.replace(/\band\b/gi, "&");
}
