/**
 * Style reminder — Mall Road Monograph: verified, display-only menu data.
 * Names and category counts are transcribed from the public Naatures Scuup Zomato menu page.
 * No prices, availability, ordering, or reservation capability is represented here.
 */
export const menuChapters = [
  { index: "01", slug: "starters", title: "Starters", note: "The first share", detail: "Crisp, smoky and tangy starters made to arrive at the centre of the table.", dishes: ["Hara Bhara Kabab", "Dahi Kabab", "Crispy Corn", "Paneer Tikka", "Dahi Cheese Kabab", "Paneer Afghani Tikka", "Veg Kathi", "Paneer 65", "Dahi Kabab Roll", "Chinese Bhel"] },
  { index: "02", slug: "soups-salads", title: "Soups & Salads", note: "Bright beginnings", detail: "Comforting soups and fresh, lighter sides for a gentler start to the meal.", dishes: ["Hot and Sour Soup", "Cream of Tomato Soup", "Manchow Soup", "Veg Corn Soup", "Clear Soup", "Mix Fruit Salad", "Onion Salad", "Cucumber Salad", "Green Salad", "Kachumber Salad"] },
  { index: "03", slug: "main-course", title: "Main Course", note: "Rich, familiar, generous", detail: "Paneer, dal and seasonal vegetable favourites for long lunches and shared dinners.", dishes: ["Kadai Paneer", "Malai Kofta", "Paneer Lababdar", "Paneer Butter Masala", "Shahi Paneer", "Handi Paneer", "Paneer Pasanda", "Matar Paneer", "Paneer Tikka Masala", "Paneer Toofani", "Veg Kofta", "Paneer Bhurji", "Paneer Methi Matar Malai", "Dal Makhani", "Dal Tadka", "Dal Fry", "Punjabi Dal Tadka", "Matar Mushroom", "Mix Veg", "Dum Aloo", "Dum Aloo Achari", "Dum Aloo Stuffed", "Jeera Aloo", "Stuffed Tomato", "Aloo Gobi Matar", "Kofta Shaam Savera", "Veg Jaipuri", "Veg Jalfrezi", "Kashmiri Dum Aloo", "Bhojpuri Dum Aloo", "Pindi Chana", "Mushroom Masala", "Stuffed Capsicum", "Capsicum Potato"] },
  { index: "04", slug: "breads", title: "Breads", note: "Made for every spoonful", detail: "Tandoor breads and familiar parathas to pair alongside a generous main course.", dishes: ["Stuffed Aloo Paratha", "Stuffed Onion Paratha", "Plain Roti", "Butter Roti", "Butter Naan", "Plain Naan", "Missi Roti", "Lachha Paratha", "Stuffed Naan", "Garlic Naan", "Tandoori Paneer Paratha", "Stuffed Mirchi Paratha"] },
  { index: "05", slug: "rice-biryani", title: "Rice & Biryani", note: "A fragrant chapter", detail: "Fragrant rice plates, from simple bowls to celebratory biryani.", dishes: ["Veg Biryani", "Veg Pulao", "Plain Rice", "Jeera Rice", "Kashmiri Pulao", "Hyderabadi Dum Biryani", "Onion Rice", "Lemon Rice", "Curd Rice", "Cheese Pulao", "Peas Pulao"] },
  { index: "06", slug: "south-indian", title: "South Indian", note: "Crisp comfort", detail: "The familiar pull of dosa and uttapam, with chutney on the side.", dishes: ["Paneer Dosa", "Uttapam", "Plain Dosa"] },
  { index: "07", slug: "chinese", title: "Chinese", note: "Wok-tossed energy", detail: "Three Indo-Chinese favourites with crunch, spice and satisfying sauces.", dishes: ["Veg Manchurian", "Chilli Paneer", "Paneer Manchurian"] },
  { index: "08", slug: "fried-rice-noodles", title: "Fried Rice & Noodles", note: "The wok chapter", detail: "Rice and noodles for a table that wants its flavours bright, fast and saucy.", dishes: ["Fried Rice", "Schezwan Rice", "Veg Chowmein", "Chilli Garlic Noodles", "Paneer Chowmein", "American Chopsuey", "Hakka Noodles with Gravy", "Schezwan Noodles", "Singapuri Noodles", "Triple Schezwan Noodles"] },
  { index: "09", slug: "pizza-pasta", title: "Pizza & Pasta", note: "Cheese pulls & twirls", detail: "Pizzas, pasta and quick café favourites for a crowd-pleasing table mood.", dishes: ["Cheese Burst Pizza [10 Inches]", "Pizza Indiana [10 Inches]", "Pizza Special [10 Inches]", "Chilli Paneer Pizza [10 Inches]", "Paneer Pizza [10 Inches]", "Corn Pizza [10 Inches]", "Cheese Mushroom Pizza [10 Inches]", "Cheese Pizza [10 Inches]", "Alfredo White Sauce", "Arrabiata ( Red Sauce)", "Rosato Pink Sauce Pasta", "Rosato Green Sauce Pasta", "Classic Vada Pav", "Spicy Vada Pav", "Cheese Vada Pav"] },
  { index: "10", slug: "burgers-sandwiches", title: "Burgers & Sandwiches", note: "Toasted and stacked", detail: "Soft buns, crunchy fillings and quick café classics for in-between cravings.", dishes: ["Veg Burger", "Cheese Burger", "Double Cheese Burger", "Veg Sandwich", "Bombay Bachelors Sandwich", "Cheese Bombay Bachelors Sandwich", "Paneer Sandwich", "Veg Corn Sandwich"] },
  { index: "11", slug: "snacks", title: "Snacks", note: "Quick-table favourites", detail: "Crisp, shareable snacks that keep conversation at the centre of the table.", dishes: ["Honey Chilli Potato", "Chole Bhature", "Cheese Balls", "Pav Bhaji", "Veg Chaap", "Masala Fries", "Cheese Fries", "French Fries", "Three Pepper Potato", "Garlic Bread", "Cheese Garlic Bread", "Potato Cheese Balls", "Veg Cutlet", "Manchurian Puff", "Paneer Pakoda", "Mix Pakoda"] },
  { index: "12", slug: "rolls", title: "Rolls", note: "A quick wrap", detail: "Compact, flavour-filled rolls made for a quick bite at any hour.", dishes: ["Veg Spring Roll", "Chilli Paneer Roll", "Paneer Roll", "Paneer Kathi Roll"] },
  { index: "13", slug: "maggi", title: "Maggi", note: "Easy comfort", detail: "Noodle comfort, from plain and familiar to paneer and mushroom-led bowls.", dishes: ["Plain Maggi", "Vegetable Maggi", "Paneer Maggi", "Mushroom Maggi"] },
  { index: "14", slug: "accompaniments", title: "Accompaniments", note: "The small essentials", detail: "Cool raitas and crisp papad to round out the main table.", dishes: ["Plain Raita", "Mix Veg Raita", "Mix Fruit Raita", "Pineapple Raita", "Boondi Raita", "Mint Raita", "Fried Papad", "Papad Dry", "Masala Papad"] },
  { index: "15", slug: "ice-creams", title: "Desserts & Ice Creams", note: "The sweet finish", detail: "Fruit-led scoops, creamy classics and a generous reason to make room for another dessert.", dishes: ["American Nuts Ice Cream", "Belgian Chip Chocolate Ice Cream", "Black Current Ice Cream", "Anjeer Badam Ice Cream", "Trutti Fruitti Ice Cream", "Butterscotch Ice Cream", "Sitafal Ice Cream", "Litchi Ice Cream", "Royal Rose Ice Cream", "Tender Coconut Ice Cream", "Kesar Pista Ice Cream", "Soothing Strawberry Ice Cream", "Belgian Chocolate Ice Cream", "Cool Kiwi Ice Cream", "Orange Ice Cream", "Pineapple Ice Cream", "Vanilla Ice Cream", "Alphonso Ice Cream", "Jamun Ice Cream", "Pan Ice Cream", "Chip Chocolate Ice Cream", "Chocolate Mud Ice Cream", "Guava Ice Cream"] },
  { index: "16", slug: "drinks", title: "Drinks & Shakes", note: "Sip slowly", detail: "Coffee, tea, mocktails and shakes to stretch the conversation a little longer.", dishes: ["Cold Coffee with Vanilla Ice Cream", "Black Tea", "Hot Coffee", "Black Coffee", "Cold Coffee", "Iced Tea", "Sparkling Soda with Vanilla Ice Cream", "Virgin Mojito", "Orange Mojito", "Fresh Lime", "Kiwi Blast", "Green Apple", "Tom and Jerry", "Peach and Apricot", "Orange Mint", "Blue Lagoon", "Bubble Gum", "Blueberry", "Spicy Mango", "Spicy Lemonade", "Watermelon", "Triple Shake", "Special Flavours", "Oreo Mud Shake", "Kit Kat Break Shake", "Ferro Rocher Shake", "Pineapple Shake", "Strawberry Shake", "Butter Shake", "Banana Shake", "Mango Shake"] },
  { index: "17", slug: "bakery-specials", title: "Bakery Specials", note: "A final little extra", detail: "A baked savoury to carry the craving just a little further.", dishes: ["Paneer Puff Patties"] },
] as const;

export const menuItemCount = menuChapters.reduce((count, chapter) => count + chapter.dishes.length, 0);
