import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const orbit = readFileSync(resolve(process.cwd(), "client/src/components/IceCreamOrbit.tsx"), "utf8");
const home = readFileSync(resolve(process.cwd(), "client/src/pages/Home.tsx"), "utf8");
const languageCopy = readFileSync(resolve(process.cwd(), "client/src/lib/language-copy.ts"), "utf8");

describe("full-screen GSAP ice-cream sequence", () => {
  it("uses cleaned desktop and mobile video sources derived from the approved frames", () => {
    expect(orbit).toContain("mango-ice-cream-1440p-clean-scrub_59b5e815.mp4");
    expect(orbit).toContain("mango-ice-cream-portrait-mobile_4b0f7dd0.mp4");
    expect(orbit).toContain('media="(max-width: 767px)"');
    expect(orbit).toContain("isChromeDesktopSiteViewport");
    expect(orbit).toContain('data-cinematic-layout={desktopSiteLayout ? "desktop" : "mobile"}');
    expect(orbit).toContain('{!desktopSiteLayout && <source media="(max-width: 767px)"');
    expect(orbit).toContain("ezgif-frame-001_c0bf1371.png");
    expect(orbit).toContain("<video");
    expect(orbit).toContain('preload="auto"');
    expect(orbit).not.toContain("MANGO_SCROLL_FRAMES");
  });

  it("uses sequential native playback for a restrained catch-up glide rather than random seeking", () => {
    expect(orbit).toContain('from "gsap/ScrollTrigger"');
    expect(orbit).toContain("ScrollTrigger.create");
    expect(orbit).toContain("const advanceToTarget");
    expect(orbit).toContain("video.playbackRate = delta > 3 ? 2 : delta > 1 ? 1.45 : 1.08");
    expect(orbit).toContain("void video.play()");
    expect(orbit).toContain("window.requestAnimationFrame");
    expect(orbit).toContain("const releaseCompletionLockRef");
    expect(orbit).toContain("const completionLockedRef");
    expect(orbit).toContain("onLeave: (self)");
    expect(orbit).toContain("self.scroll(self.end - 2)");
    expect(orbit).toContain("const exitCompletedCinematic");
    expect(orbit).toContain("trigger.kill(true)");
    expect(orbit).toContain("completionLockedRef.current ? video.duration");
    expect(orbit).toContain("video.ended || video.currentTime >= video.duration - 0.01");
    expect(orbit).toContain("onEnded={() => releaseCompletionLockRef.current?.()}");
    expect(orbit).toContain("window.innerHeight * 3.75");
    expect(orbit).toContain('pin: ".ice-orbit__stage"');
  });

  it("adds a clean desktop narrative while creating a distraction-free, tightly focused mobile hero", () => {
    expect(orbit).toContain('className="ice-orbit__loading"');
    expect(orbit).toContain('const CINEMATIC_GROUND = "#b8babc"');
    expect(orbit).toContain('background:${CINEMATIC_GROUND} url("/manus-storage/ezgif-frame-001_c0bf1371.png") center/cover no-repeat');
    expect(orbit).toContain("prefers-reduced-motion");
    expect(orbit).toContain("@media(max-width:767px){.ice-orbit__stage{perspective:none;background:${CINEMATIC_GROUND}}");
    expect(orbit).toContain(".ice-orbit__video{object-fit:cover;object-position:50% 50%");
    expect(orbit).toContain('from "framer-motion"');
    expect(orbit).toContain("const storyProgress = useMotionValue(0)");
    expect(orbit).toContain("const copy = cinematicCopy[language]");
    expect(languageCopy).toContain("The Mall · Kanpur");
    expect(languageCopy).toContain("Kanpur's first live ice-cream parlour");
    expect(languageCopy).toContain("Live ice cream");
    expect(languageCopy).toContain("Scroll to unfreeze");
    expect(languageCopy).toContain("Kanpur's first");
    expect(languageCopy).toContain("One place.");
    expect(languageCopy).toContain("#FREEZETHEHAPPINESS");
    expect(orbit).toContain("ice-orbit__story");
    expect(orbit).toContain("background:${CINEMATIC_GROUND}");
    expect(orbit).toContain("color:rgb(47 38 34)!important");
    expect(orbit).toContain(".ice-orbit__story-card--origin{top:18%;left:clamp(1.25rem,5vw,5.25rem);text-align:left}");
    expect(orbit).toContain(".ice-orbit__story-card--right{top:24%;right:clamp(1.25rem,5vw,5.25rem)");
    expect(orbit).toContain(".ice-orbit__story-card--end{right:clamp(1.25rem,5vw,5.25rem);bottom:14%;left:auto;text-align:right}");
    expect(orbit).not.toContain("-webkit-mask-image");
    expect(orbit).not.toContain("ice-orbit__stage::after");
    expect(orbit).not.toContain("radial-gradient");
    expect(orbit).not.toContain("linear-gradient");
    expect(orbit).not.toContain("filter:");
    expect(orbit).not.toContain("text-shadow:");
    expect(orbit).toContain('font-family:"Playfair Display",Georgia,serif');
    expect(orbit).toContain("font-family:Montserrat,ui-sans-serif,system-ui,sans-serif");
    expect(orbit).toContain(".ice-orbit__video{object-fit:cover;object-position:50% 50%;background-color:${CINEMATIC_GROUND};transform:translate3d(var(--mobile-camera-x,0vw),var(--mobile-camera-y,0vh),0) scale(2.9)");
    expect(orbit).toContain(".ice-orbit__video{transform:scale(2.72)!important;transition:none!important}");
    expect(orbit).toContain(".ice-orbit__story{display:block;z-index:6;pointer-events:none}");
    expect(orbit).toContain('.ice-orbit__story-card[data-active="true"]{display:block!important;opacity:1!important');
    expect(orbit).toContain('copy.originMobile.split("|")');
    expect(orbit).toContain('copy.parlourMobile.split("|")');
    expect(orbit).toContain('copy.cravingMobile.split("|")');
    expect(orbit).toContain('copy.varietyMobile.split("|")');
    expect(orbit).toContain('copy.endMobile.split("|")');
    expect(orbit).toContain("transform:translate3d(-50%,0,44px) rotateX(5deg) rotateY(-4deg)!important");
    expect(orbit).toContain("perspective:980px!important");
    expect(languageCopy).toContain("The Naatures Scuup way.");
    expect(orbit).toContain(".ice-orbit__story-card--origin,.ice-orbit__story-card--left,.ice-orbit__story-card--right{top:64%!important");
    expect(orbit).toContain(".ice-orbit__story-card--variety,.ice-orbit__story-card--end{top:59%!important");
    expect(orbit).toContain(".ice-orbit__story-copy{font-size:.68rem!important");
    expect(orbit).toContain("@media(min-width:768px){.ice-orbit__stage{perspective:1150px!important");
    expect(orbit).toContain('.ice-orbit__stage[data-cinematic-layout="desktop"] .ice-orbit__video{object-fit:cover!important');
    expect(orbit).toContain('.ice-orbit__stage[data-cinematic-layout="desktop"] .ice-orbit__story-card{display:block!important');
    expect(orbit).toContain('.ice-orbit__stage[data-cinematic-layout="desktop"] .ice-orbit__mobile-title{display:none!important}');
    expect(orbit).toContain(".ice-orbit__video{object-fit:cover!important;object-position:center!important}");
    expect(orbit).toContain("const CAMERA_COMPOSITIONS");
    expect(orbit).toContain('"--camera-x"');
    expect(orbit).toContain('"--camera-rotation"');
    expect(orbit).toContain('"--camera-origin"');
    expect(orbit).toContain('"--mobile-camera-x"');
    expect(orbit).toContain("transition:transform var(--camera-duration,2000ms) cubic-bezier(.22,1,.36,1)");
    expect(orbit).toContain(".ice-orbit__story-card--origin{top:18%!important");
    expect(orbit).toContain(".ice-orbit__story-card--left{top:25%!important");
    expect(orbit).toContain(".ice-orbit__story-card--left .ice-orbit__story-title--label{padding:.42rem .54rem .48rem!important;font-size:clamp(2.1rem,3.9vw,4.2rem)!important");
    expect(orbit).toContain(".ice-orbit__story-card--end{top:auto!important");
    expect(orbit).not.toContain('className="ice-orbit__scroll-button"');
    expect(orbit).not.toContain('aria-label={copy.continue}');
    expect(orbit).toContain("const handleScrollAdvance");
    expect(orbit).toContain("window.scrollTo");
    expect(orbit).toContain("ice-orbit__scroll-prompt");
    expect(orbit).toContain('aria-label={copy.nextStory}');
    expect(orbit).toContain('{copy.scrollPrompt}</button>');
  });

  it("keeps the sequence before Drag It on Home", () => {
    expect(home).toContain("<IceCreamOrbit />");
    expect(home.indexOf("<IceCreamOrbit />")).toBeLessThan(home.indexOf('<OrganicWaveDivider tone="cream-to-maroon" />'));
    expect(home.indexOf('<OrganicWaveDivider tone="cream-to-maroon" />')).toBeLessThan(home.indexOf("<DragFoodCanvas"));
    expect(home).toContain('scrollToId("#location")');
    expect(home).not.toContain('className="story-section section-pad"');
  });

  it("uses five evenly spaced story checkpoints with continuous one-card coverage and a five-dot public rail", () => {
    expect(orbit).toContain("STORY_SCROLL_POINTS");
    expect(orbit).toContain("const STORY_CHECKPOINT_COUNT = 5");
    expect(orbit).toContain("const STORY_SCROLL_START = 0.02");
    expect(orbit).toContain("const STORY_SCROLL_END = 0.88");
    expect(orbit).toContain("(STORY_SCROLL_END - STORY_SCROLL_START) * index");
    expect(orbit).toContain("requestCheckpointAdvance");
    expect(orbit).toContain("const CHECKPOINT_GLIDE_MS = 780");
    expect(orbit).toContain("const CHECKPOINT_IDLE_MS = 120");
    expect(orbit).toContain("const easedProgress = 1 - Math.pow(1 - progress, 3)");
    expect(orbit).toContain("checkpointAnimationRef");
    expect(orbit).toContain('window.addEventListener("wheel", handleCheckpointWheel, { passive: false, capture: true })');
    expect(orbit).toContain("onTouchEnd={handleTouchEnd}");
    expect(orbit).toContain("checkpointInputLockedRef");
    expect(orbit).toContain("const checkpointInputDirectionRef");
    expect(orbit).toContain("checkpointInputDirectionRef.current !== direction");
    expect(orbit).toContain("window.cancelAnimationFrame(checkpointAnimationRef.current)");
    expect(orbit).toContain("const [cameraReadyForMotion, setCameraReadyForMotion] = useState(false)");
    expect(orbit).toContain('"--camera-duration": `${cameraReadyForMotion ? camera.duration : 0}ms`');
    expect(orbit).toContain("getStoryCheckpoint");
    expect(orbit).toContain("return closestStop");
    expect(orbit).toContain("const cardStyle");
    expect(orbit).toContain("opacity: activeCheckpoint === index ? 1 : 0");
    expect(orbit).toContain("ice-orbit__checkpoint-rail");
    expect(orbit).toContain('["01", "02", "03", "04", "05"]');
    expect(orbit).toContain(' / 05</span>');
    expect(orbit).toContain("perspective:1150px");
    expect(orbit).toContain("transform-style:preserve-3d");
    expect(orbit).toContain("@media(hover:hover) and (pointer:fine)");
    expect(orbit).toContain('data-active={activeCheckpoint === 0}');
    expect(orbit).toContain('.ice-orbit__story-card[data-active="true"][data-interacting="true"] .ice-orbit__story-glyph');
    expect(orbit).toContain("handleStoryPointerMove");
    expect(orbit).toContain("MagneticTitle");
    expect(orbit).toContain("ice-orbit__story-title--label");
    expect(orbit).toContain("ice-orbit__story-copy--label");
    expect(languageCopy).toContain("Keep the happiness cold");
    expect(orbit).toContain("data-story-glyph");
    expect(orbit).toContain("--glyph-x");
    expect(orbit).not.toContain("ice-orbit__liquid-wake");
    expect(orbit).toContain("transform 560ms");
    expect(orbit).toContain("distance / 260");
    expect(orbit).toContain("influence * 1.05");
    expect(orbit).toContain('data-active={activeCheckpoint === 3}');
    expect(orbit).toContain('data-active={activeCheckpoint === 4}');
    expect(languageCopy).toContain("Dosas to desserts.");
    expect(languageCopy).toContain("#FREEZE THE|HAPPINESS");
  });

  it("conceals the global header while the opening sequence remains in view", () => {
    expect(orbit).toContain("setOpeningHeaderHidden");
    expect(orbit).toContain("document.documentElement.dataset.iceHeroActive");
    expect(orbit).toContain("onEnter: () => setOpeningHeaderHidden(true)");
    expect(orbit).toContain("setOpeningHeaderHidden(false)");
    expect(orbit).toContain("const postCinematicExitRef");
    expect(orbit).toContain("self.scroll() > self.end + 80");
    expect(orbit).toContain('window.addEventListener("scroll", revealHeaderAfterExit, { passive: true })');
  });
});

export {};
