/** Style reminder — Mall Road Monograph: sourced public review text is foreground content, never invented endorsement. */
import { ExternalLink, Star } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";

const mapReviewUrl = "https://www.google.com/maps/place/Naatures+Scoop/@26.4623472,80.3597621,17z/data=!4m8!3m7!1s0x399c47516510d649:0xbf89e3c0bec00bca!8m2!3d26.4623472!4d80.3597621!9m1!1b1!16s%2Fg%2F11c7sr345f?hl=en";

const reviews = [
  { name: "Mahi Seerwani", count: 345, rating: 5, text: "A lovely place to visit with friends and family. I like the ambience of this place. I ordered-", excerpt: true },
  { name: "The Ghoomne Wala", count: 197, rating: 5, text: "Overall a calm and quite place for LONERS like me. Not like RITA’s fake atmosphere. Here old age ppl sit. Have snacks. Talk. Best place in the middle of the mall road kanpur. Ample space to park car and bike. I ordered oval choco pastry. All the pastry and items are EGGLESS. Also packed two black forest.", mentioned: "Oval choco pastry · Black forest" },
  { name: "Manshi Pandey", count: 3, rating: 5, text: "Nature’s Scuup is at Mallroad chauraha . You can go to this place if your are looking for some small family gathering or a hangout with friends . It has a nice sitting arrangement. The staff is really friendly and polite . . Now coming to the food I would like to recommend you to try out their . 🍝 Green Pasta : It was rich in taste and creamy . There was a good amount of veggies in it and a plus point it was so nutritious as the sauce was made of Spinach and there was no added colour to it . The pasta did not have any smell of spinach or the taste of it it was perfectly amalgamated with with the pasta . . Recommendation : A must try ! They give it with a seasoned bread . . Price : ₹240/- . 🍲 Chilli Paneer & Singapuri Noodles : I loved the spicy flavour of the chilli paneer gravy which was perfectly gelling up with the not so spicy singapuri noodles . You should really order this as a combo to derive a perfect pleasure of taste . . Recommendation : Yassssss ! Zabardast tha . Price : chilli paneer - ₹ 240/- Singapuri noodles - ₹170/- . Apart from this you can really go and check out their wide Icecream range . The Garlic Naan is a must try with some Paneer Labadar and Dahi bade . . . You can swipe right for the full video of the menu and some drooling dishes like : Chilli Paneer , Singapuri Noodles , Italian Pasta Pizza , Garlic Naan , Paneer Labadar , Dahi bada , Gobhi Manchurian , Dahi Kabab , Bombay Bachelor Sandwich , Dahi cheese kabab roll , chilli paneer Dosa and Fried Icecream 😍 .", mentioned: "Green pasta · Chilli paneer" },
  { name: "Sakeena Abbas", count: 82, rating: 5, text: "This place offers a great variety of dishes ranging from desi indian dishes to chinese, italian and desserts. The interiors are simple. There is ample space to sit. The food too is good specially the ROSOTO PASTA (green sauce),Singapori noodles and Chilli paneer. The best thing about the pasta was that the green colour was natural (of the spinach used in the sauce & it didn't even taste like spinach😍) I just loved it. All the three items are strongly recommended to try on your next visit here. Do try the dahi ke sholay, dahi vada & sandwiches also🤤 The service is good and the rates too are fine.", mentioned: "Rosoto pasta · Chilli paneer" },
  { name: "Simerpreet Kaur", count: 26, rating: 5, text: "The place is great for a normal hangout with friends and family. The live ice cream is great. The Oreo mud shake is good. The cheesy fries too.. the overall experience is good. The interior is nice. The service was fine. The prices are pocket friendly. And the variety is good for deserts and shakes.", mentioned: "Oreo mud shake · Cheesy fries" },
  { name: "Nandani Riyaa", count: 9, rating: 5, text: "The dosa of this shop is my favourite i always came here just for dosa. Visit this place if u want to eat south India", mentioned: "Dosa" },
] as const;

export function GoogleReviews() {
  const reduceMotion = useReducedMotion();
  return <section id="reviews" className="reviews-section section-pad print-paper" aria-labelledby="reviews-title"><div className="reviews-head reviews-head--proof"><div><p className="eyebrow eyebrow--maroon">04 / Selected diner proof</p><h2 id="reviews-title" className="print-ink">Diner reviews<br />& <i>social proof.</i></h2></div><div><span className="review-summary" aria-label="Six positive public Google Maps reviews"><Star size={13} fill="currentColor" /> 6 positive public reviews</span><p>Authentic, positive public reviews from the Naatures Scuup Google Maps listing. Review wording is preserved exactly as published.</p><a className="inline-link" href={mapReviewUrl} target="_blank" rel="noreferrer">Read all on Google Maps <ExternalLink size={14} /></a></div></div><div className="review-grid review-grid--proof">{reviews.map((review, index) => <motion.article className="review-card review-card--proof print-edge-boil" key={review.name} initial={reduceMotion ? false : { opacity: 0, y: 24 }} whileInView={reduceMotion ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.16 }} transition={{ duration: 0.46, delay: (index % 3) * 0.06, ease: [0.23, 1, 0.32, 1] }}><header><div><strong>{review.name}</strong><span>{review.count} Google reviews</span></div><span className="review-rating">{review.rating}.0 <Star size={12} fill="currentColor" /></span></header><blockquote className="review-preview">“{review.text}”</blockquote><details className="review-expand"><summary>Read public review</summary><blockquote>“{review.text}”</blockquote></details>{"excerpt" in review && review.excerpt === true && <p className="review-note">Google Maps displays this review as an excerpt.</p>}{"mentioned" in review && review.mentioned && <div className="review-mentioned"><span>Mentioned dish</span><strong>{review.mentioned}</strong></div>}<a href={mapReviewUrl} target="_blank" rel="noreferrer">Google Maps source <ExternalLink size={12} /></a></motion.article>)}</div></section>;
}
