/** Style reminder — Mall Road Monograph: sourced public review text is foreground content, never invented endorsement. */
import { ExternalLink, Star } from "lucide-react";

const mapReviewUrl = "https://www.google.com/maps/place/Naatures+Scoop/@26.4623472,80.3597621,17z/data=!4m8!3m7!1s0x399c47516510d649:0xbf89e3c0bec00bca!8m2!3d26.4623472!4d80.3597621!9m1!1b1!16s%2Fg%2F11c7sr345f?hl=en";

const reviews = [
  { name: "Mahi Seerwani", count: 345, rating: 5, text: "A lovely place to visit with friends and family. I like the ambience of this place. I ordered-", excerpt: true },
  { name: "The Ghoomne Wala", count: 197, rating: 5, text: "Overall a calm and quite place for LONERS like me. Not like RITA’s fake atmosphere. Here old age ppl sit. Have snacks. Talk. Best place in the middle of the mall road kanpur. Ample space to park car and bike. I ordered oval choco pastry. All the pastry and items are EGGLESS. Also packed two black forest." },
  { name: "Food_milai_jodi", count: 172, rating: 3, text: "Service was dissatisfied 💔💔You can't spend more time there. Bas khao piyo niklo wala haal hai. Potato cheese balls was good in taste dosa taste was not good. It's famous for ice-cream roll and shakes. Cold coffee with ice cream was better.." },
  { name: "sakeena abbas", count: 82, rating: 5, text: "This place offers a great variety of dishes ranging from desi indian dishes to chinese, italian and desserts. The interiors are simple. There is ample space to sit. The food too is good specially the ROSOTO PASTA (green sauce),Singapori noodles and Chilli paneer. The best thing about the pasta was that the green colour was natural (of the spinach used in the sauce & it didn't even taste like spinach😍) I just loved it. All the three items are strongly recommended to try on your next visit here. Do try the dahi ke sholay, dahi vada & sandwiches also🤤 The service is good and the rates too are fine." },
  { name: "Simerpreet Kaur", count: 26, rating: 5, text: "The place is great for a normal hangout with friends and family. The live ice cream is great. The Oreo mud shake is good. The cheesy fries too.. the overall experience is good. The interior is nice. The service was fine. The prices are pocket friendly. And the variety is good for deserts and shakes." },
  { name: "nandani riyaa", count: 9, rating: 5, text: "The dosa of this shop is my favourite i always came here just for dosa. Visit this place if u want to eat south India" },
] as const;

export function GoogleReviews() {
  return <section id="reviews" className="reviews-section section-pad" aria-labelledby="reviews-title"><div className="reviews-head"><div><p className="eyebrow eyebrow--maroon">04 / Google Maps voices</p><h2 id="reviews-title">Six table<br /><i>notes.</i></h2></div><div><p>Public reviews from the six highest visible reviewer-count profiles found on the restaurant’s Google Maps listing. They are shown verbatim; the 3-star review is intentionally retained.</p><a className="inline-link" href={mapReviewUrl} target="_blank" rel="noreferrer">Read all on Google Maps <ExternalLink size={14} /></a></div></div><div className="review-grid">{reviews.map((review) => <article className="review-card" key={review.name}><header><div><strong>{review.name}</strong><span>{review.count} Google reviews</span></div><span className="review-rating">{review.rating}.0 <Star size={12} fill="currentColor" /></span></header><blockquote className="review-preview">“{review.text}”</blockquote><details className="review-expand"><summary>Read public review</summary><blockquote>“{review.text}”</blockquote></details>{"excerpt" in review && review.excerpt === true && <p className="review-note">Google Maps displays this review as an excerpt.</p>}<a href={mapReviewUrl} target="_blank" rel="noreferrer">Google Maps source <ExternalLink size={12} /></a></article>)}</div></section>;
}
