/** Style reminder — Mall Road Monograph: sourced public review text is foreground content, never invented endorsement. */
import { ExternalLink, Star } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import { OrganicWaveDivider } from "@/components/OrganicWaveDivider";
import { useLanguage } from "@/contexts/LanguageContext";
import { reviewCopy } from "@/lib/language-copy";
import { localizeMenuDishName } from "@/lib/language-copy";

const mapReviewUrl = "https://www.google.com/maps/place/Naatures+Scoop/@26.4623472,80.3597621,17z/data=!4m8!3m7!1s0x399c47516510d649:0xbf89e3c0bec00bca!8m2!3d26.4623472!4d80.3597621!9m1!1b1!16s%2Fg%2F11c7sr345f?hl=en";

const reviews = [
  { name: "Mahi Seerwani", count: 345, rating: 5, text: "A lovely place to visit with friends and family. I like the ambience of this place. I ordered-", translation: "दोस्तों और परिवार के साथ आने के लिए प्यारी जगह। मुझे यहाँ का माहौल पसंद आया। मैंने ऑर्डर किया—", excerpt: true },
  { name: "The Ghoomne Wala", count: 197, rating: 5, text: "Overall a calm and quite place for LONERS like me. Not like RITA’s fake atmosphere. Here old age ppl sit. Have snacks. Talk. Best place in the middle of the mall road kanpur. Ample space to park car and bike. I ordered oval choco pastry. All the pastry and items are EGGLESS. Also packed two black forest.", translation: "कुल मिलाकर, मेरे जैसे अकेले आने वालों के लिए शांत और सुकूनभरी जगह। यहाँ बुज़ुर्ग लोग बैठते, स्नैक्स लेते और बातें करते हैं। कानपुर की मॉल रोड के बीच अच्छी जगह है तथा कार और बाइक पार्किंग के लिए पर्याप्त स्थान है। मैंने ओवल चोको पेस्ट्री ऑर्डर की। सभी पेस्ट्री और आइटम एगलेस हैं। दो ब्लैक फॉरेस्ट भी पैक कराए।", mentioned: "Oval choco pastry · Black forest" },
  { name: "Manshi Pandey", count: 3, rating: 5, text: "Nature’s Scuup is at Mallroad chauraha . You can go to this place if your are looking for some small family gathering or a hangout with friends . It has a nice sitting arrangement. The staff is really friendly and polite . . Now coming to the food I would like to recommend you to try out their . 🍝 Green Pasta : It was rich in taste and creamy . There was a good amount of veggies in it and a plus point it was so nutritious as the sauce was made of Spinach and there was no added colour to it . The pasta did not have any smell of spinach or the taste of it it was perfectly amalgamated with with the pasta . . Recommendation : A must try ! They give it with a seasoned bread . . Price : ₹240/- . 🍲 Chilli Paneer & Singapuri Noodles : I loved the spicy flavour of the chilli paneer gravy which was perfectly gelling up with the not so spicy singapuri noodles . You should really order this as a combo to derive a perfect pleasure of taste . . Recommendation : Yassssss ! Zabardast tha . Price : chilli paneer - ₹ 240/- Singapuri noodles - ₹170/- . Apart from this you can really go and check out their wide Icecream range . The Garlic Naan is a must try with some Paneer Labadar and Dahi bade . . . You can swipe right for the full video of the menu and some drooling dishes like : Chilli Paneer , Singapuri Noodles , Italian Pasta Pizza , Garlic Naan , Paneer Labadar , Dahi bada , Gobhi Manchurian , Dahi Kabab , Bombay Bachelor Sandwich , Dahi cheese kabab roll , chilli paneer Dosa and Fried Icecream 😍 .", translation: "नेचर्स स्कूप मॉल रोड चौराहे पर है और छोटी फैमिली गेदरिंग या दोस्तों के साथ हैंगआउट के लिए अच्छी जगह है। बैठने की व्यवस्था अच्छी है और स्टाफ बहुत मित्रवत व विनम्र है। खाने में ग्रीन पास्ता ज़रूर ट्राई करें: यह रिच और क्रीमी था, इसमें अच्छी मात्रा में सब्ज़ियाँ थीं तथा पालक के सॉस और बिना किसी अतिरिक्त रंग के कारण पौष्टिक लगा। पास्ता में पालक की गंध या स्वाद नहीं था और इसे सीज़न्ड ब्रेड के साथ दिया जाता है। कीमत ₹240। चिल्ली पनीर और सिंगापुरी नूडल्स का कॉम्बो भी बहुत अच्छा लगा—स्पाइसी ग्रेवी और हल्के नूडल्स साथ में शानदार रहे। चिल्ली पनीर ₹240 और सिंगापुरी नूडल्स ₹170। आइसक्रीम रेंज भी देखें; गार्लिक नान, पनीर लबाबदार और दही बड़े भी ट्राई करने लायक हैं।", mentioned: "Green pasta · Chilli paneer" },
  { name: "Sakeena Abbas", count: 82, rating: 5, text: "This place offers a great variety of dishes ranging from desi indian dishes to chinese, italian and desserts. The interiors are simple. There is ample space to sit. The food too is good specially the ROSOTO PASTA (green sauce),Singapori noodles and Chilli paneer. The best thing about the pasta was that the green colour was natural (of the spinach used in the sauce & it didn't even taste like spinach😍) I just loved it. All the three items are strongly recommended to try on your next visit here. Do try the dahi ke sholay, dahi vada & sandwiches also🤤 The service is good and the rates too are fine.", translation: "यहाँ देसी भारतीय व्यंजनों से लेकर चाइनीज़, इटैलियन और डेज़र्ट तक अच्छी विविधता है। इंटीरियर सरल है और बैठने की पर्याप्त जगह है। खाना अच्छा है, खासकर रोसाटो पास्ता (ग्रीन सॉस), सिंगापुरी नूडल्स और चिल्ली पनीर। पास्ता की सबसे अच्छी बात यह थी कि हरा रंग प्राकृतिक था—सॉस में पालक होने पर भी उसका स्वाद नहीं आया। अगली विज़िट में ये तीनों आइटम ज़रूर ट्राई करें। दही के शोले, दही वड़ा और सैंडविच भी ट्राई करें। सर्विस अच्छी है और रेट भी ठीक हैं।", mentioned: "Rosoto pasta · Chilli paneer" },
  { name: "Simerpreet Kaur", count: 26, rating: 5, text: "The place is great for a normal hangout with friends and family. The live ice cream is great. The Oreo mud shake is good. The cheesy fries too.. the overall experience is good. The interior is nice. The service was fine. The prices are pocket friendly. And the variety is good for deserts and shakes.", translation: "दोस्तों और परिवार के साथ सामान्य हैंगआउट के लिए यह जगह अच्छी है। लाइव आइसक्रीम बहुत अच्छी है। ओरियो मड शेक और चीज़ी फ्राइज़ भी अच्छे हैं। कुल अनुभव अच्छा रहा, इंटीरियर सुंदर है, सर्विस ठीक है और कीमतें पॉकेट-फ्रेंडली हैं। डेज़र्ट और शेक्स की विविधता भी अच्छी है।", mentioned: "Oreo mud shake · Cheesy fries" },
  { name: "Nandani Riyaa", count: 9, rating: 5, text: "The dosa of this shop is my favourite i always came here just for dosa. Visit this place if u want to eat south India", translation: "इस दुकान का डोसा मेरा पसंदीदा है; मैं अक्सर सिर्फ डोसा खाने के लिए यहाँ आती हूँ। अगर आप साउथ इंडियन खाना चाहते हैं तो इस जगह पर आएँ।", mentioned: "Dosa" },
] as const;

export function GoogleReviews() {
  const reduceMotion = useReducedMotion();
  const { language } = useLanguage();
  const copy = reviewCopy[language];
  return <><section id="reviews" className="reviews-section section-pad print-paper maximalist-surface maximalist-surface--sage layered-image-depth layered-image-depth--reviews" aria-labelledby="reviews-title"><div className="maximalist-surface__forms" aria-hidden="true" /><span className="maximalist-surface__figure" aria-hidden="true">03</span><div className="reviews-head reviews-head--proof"><div><span className="maximalist-surface__label">{copy.label}</span><p className="eyebrow eyebrow--maroon">{copy.eyebrow}</p><h2 id="reviews-title" className="print-ink film-print-text film-print-text--slow">{copy.titleStart}<br />& <i>{copy.titleEnd}</i></h2></div><div><span className="review-summary" aria-label={copy.summaryAria}><Star size={13} fill="currentColor" /> {copy.summary}</span><p>{copy.intro}</p><a className="inline-link" href={mapReviewUrl} target="_blank" rel="noreferrer">{copy.allMaps} <ExternalLink size={14} /></a></div></div><div className="review-grid review-grid--proof">{reviews.map((review, index) => <motion.article className="review-card review-card--proof print-edge-boil print-edge-boil--rough maximalist-card" key={review.name} initial={reduceMotion ? false : { opacity: 0, y: 24 }} whileInView={reduceMotion ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.16 }} transition={{ duration: 0.46, delay: (index % 3) * 0.06, ease: [0.23, 1, 0.32, 1] }}><header><div><strong>{review.name}</strong><span>{review.count} {copy.count}</span></div><span className="review-rating">{review.rating}.0 <Star size={12} fill="currentColor" /></span></header><blockquote className="review-preview">“{language === "hi" ? review.translation : review.text}”</blockquote><details className="review-expand"><summary>{copy.read}</summary><blockquote>“{review.text}”</blockquote></details>{"excerpt" in review && review.excerpt === true && <p className="review-note">{copy.excerpt}</p>}{"mentioned" in review && review.mentioned && <div className="review-mentioned"><span>{copy.mentioned}</span><strong>{localizeMenuDishName(review.mentioned, language)}</strong></div>}<a href={mapReviewUrl} target="_blank" rel="noreferrer">{copy.source} <ExternalLink size={12} /></a></motion.article>)}</div></section><OrganicWaveDivider tone="sage-to-maroon" /></>;
}
