/**
 * Style reminder — Mall Road Monograph: a restrained two-page portal and typographic menu.
 * These scoped global overrides preserve the existing rice-paper and maroon system while avoiding repeated imagery.
 */
const styles = `
.site-header--hamburger{justify-content:space-between}.site-menu-toggle{display:inline-flex;align-items:center;gap:10px;margin-left:auto;padding:9px 0 9px 16px;border:0;background:transparent;color:inherit;font-size:9px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.site-menu-toggle:active{transform:scale(.97)}
.site-drawer{position:fixed;z-index:35;inset:0 0 auto;min-height:360px;padding:117px max(8.5vw,34px) 42px;background:var(--maroon-deep);color:var(--cream);transform:translateY(-104%);transition:transform 360ms var(--ease-out);box-shadow:0 20px 42px rgb(33 24 26 / 24%)}.site-drawer--open{transform:translateY(0)}.site-drawer nav{display:grid;max-width:760px;border-top:1px solid rgb(244 240 232 / 18%)}.drawer-link{display:grid;grid-template-columns:42px minmax(0,1fr) auto;align-items:center;gap:12px;min-height:75px;border-bottom:1px solid rgb(244 240 232 / 18%);font-family:"Cormorant Garamond",Georgia,serif;font-size:clamp(37px,4vw,58px);font-weight:500;letter-spacing:-.055em;line-height:.82}.drawer-link:hover,.drawer-link--active{padding-left:12px;color:var(--mango)}.drawer-link small,.drawer-link i{font-family:"Manrope",Arial,sans-serif;font-size:9px;font-style:normal;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.drawer-link small,.drawer-slogan{color:var(--mango)}.drawer-link i{color:rgb(244 240 232 / 48%)}.drawer-slogan{margin:25px 0 0;font-size:9px;font-weight:800;letter-spacing:.16em;text-transform:uppercase}
.story-grid--text{grid-template-columns:minmax(280px,.86fr) minmax(280px,.7fr);align-items:stretch}.story-manifesto{display:flex;flex-direction:column;justify-content:space-between;min-height:390px;padding:30px;background:var(--cream-deep);border-block:1px solid rgb(101 27 43 / 25%);color:var(--maroon-deep)}.story-manifesto span,.story-manifesto small{color:var(--maroon);font-size:9px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.story-manifesto p{margin:auto 0;font-family:"Cormorant Garamond",Georgia,serif;font-size:clamp(44px,5.6vw,78px);font-weight:500;letter-spacing:-.06em;line-height:.83}.experience-section--text{padding-bottom:clamp(84px,11vw,150px)}.experience-typographic{display:grid;grid-template-columns:1.2fr .8fr auto;gap:clamp(28px,5vw,80px);align-items:end;max-width:1440px;margin:auto}.experience-large-word{align-self:stretch;margin:0;color:rgb(244 240 232 / 10%);font-family:"Cormorant Garamond",Georgia,serif;font-size:clamp(120px,17vw,288px);font-style:italic;letter-spacing:-.1em;line-height:.63}.experience-typographic h3{color:var(--cream);font-size:clamp(56px,6.2vw,95px)}.experience-typographic>div>p:not(.eyebrow){max-width:320px;margin:27px 0;color:rgb(244 240 232 / 70%);font-size:13px;line-height:1.8}.experience-typographic>span{align-self:stretch;display:flex;align-items:flex-end;padding-bottom:8px;color:rgb(244 240 232 / 46%);font-size:9px;font-weight:800;letter-spacing:.15em;line-height:1.65;text-align:right;text-transform:uppercase;writing-mode:vertical-rl}
.footer-identity--text{gap:11px}.footer-identity--text .footer-title{color:var(--cream);font-family:"Cormorant Garamond",Georgia,serif;font-size:35px;font-weight:500;letter-spacing:-.065em;text-transform:none}.footer-identity--text a{color:var(--mango);font-size:9px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}
.menu-page{padding-top:86px}.menu-page-hero{padding-top:clamp(90px,12vw,168px);padding-bottom:clamp(70px,9vw,120px);background:var(--cream)}.menu-page-hero__grid{display:grid;grid-template-columns:1.12fr .72fr;gap:clamp(42px,10vw,155px);align-items:end;max-width:1250px;margin:auto}.menu-page h1{margin:0;color:var(--maroon-deep);font-family:"Cormorant Garamond",Georgia,serif;font-size:clamp(74px,10vw,152px);font-weight:500;letter-spacing:-.075em;line-height:.78}.menu-page h1 i{font-weight:400}.menu-page-hero__grid>div{padding-bottom:8px}.menu-page-hero__grid>div p{max-width:365px;margin:0;font-size:14px;line-height:1.82}.menu-page-hero__grid>div span{display:block;margin-top:22px;color:var(--maroon);font-size:9px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.menu-page-index{display:flex;flex-wrap:wrap;gap:8px 18px;max-width:1250px;margin:62px auto 0;padding-top:19px;border-top:1px solid rgb(33 24 26 / 18%)}.menu-page-index a{display:inline-flex;gap:6px;align-items:baseline;color:var(--maroon);font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.menu-page-index small{color:rgb(101 27 43 / 55%);font-size:8px}
.menu-page-list{padding-top:clamp(80px,11vw,148px);padding-bottom:clamp(96px,12vw,168px)}.menu-page-category{display:grid;grid-template-columns:minmax(250px,.68fr) minmax(360px,1.32fr);gap:clamp(44px,8vw,124px);max-width:1250px;margin:auto;padding:clamp(64px,8vw,110px) 0;border-top:1px solid rgb(33 24 26 / 18%);scroll-margin-top:100px}.menu-page-category:last-child{border-bottom:1px solid rgb(33 24 26 / 18%)}.menu-page-category header h2{margin-top:8px;font-size:clamp(49px,5.7vw,86px)}.menu-page-category header>p:last-child{max-width:325px;margin:25px 0 0;font-size:13px;line-height:1.8}.menu-page-category ol{display:grid;grid-template-columns:1fr 1fr;gap:0 24px;margin:0;padding:0;list-style:none;border-top:1px solid rgb(33 24 26 / 16%)}.menu-page-category li{display:grid;grid-template-columns:28px 1fr;align-items:baseline;gap:8px;min-height:62px;padding:15px 0;border-bottom:1px solid rgb(33 24 26 / 16%)}.menu-page-category li>span{padding-top:4px;color:var(--maroon);font-size:8px;font-weight:800;letter-spacing:.11em}.menu-page-category li strong{font-family:"Cormorant Garamond",Georgia,serif;font-size:clamp(25px,2.2vw,33px);font-weight:500;letter-spacing:-.045em;line-height:.9}.menu-page-closing{display:flex;align-items:flex-end;justify-content:space-between;gap:44px;padding-top:clamp(85px,11vw,152px);padding-bottom:clamp(85px,11vw,140px);background:var(--maroon-deep);color:var(--cream)}.menu-page-closing h2{color:var(--cream)}.menu-page-closing__actions{display:flex;flex-wrap:wrap;align-items:center;gap:21px}.menu-page-closing .button--cream{background:var(--cream);color:var(--maroon-deep)}
@media(max-width:900px){.story-grid--text{grid-template-columns:1.05fr .75fr}.menu-page-hero__grid,.menu-page-category{grid-template-columns:.86fr 1.14fr;gap:48px}.menu-page-category ol{grid-template-columns:1fr}}
@media(max-width:640px){.site-menu-toggle{gap:7px;padding-left:12px;font-size:8px}.site-drawer{min-height:325px;padding:101px 22px 29px}.drawer-link{grid-template-columns:31px 1fr auto;min-height:62px;font-size:40px}.drawer-link i{font-size:7px}.story-grid--text{display:block}.story-manifesto{min-height:285px;margin-top:26px;padding:23px}.story-manifesto p{font-size:58px}.experience-typographic{grid-template-columns:1fr;gap:18px}.experience-large-word{font-size:164px}.experience-typographic h3{font-size:64px}.experience-typographic>span{display:none}.menu-page{padding-top:76px}.menu-page-hero{padding-top:76px;padding-bottom:69px}.menu-page-hero__grid{display:block}.menu-page h1{font-size:clamp(67px,17vw,91px)}.menu-page-hero__grid>div{margin-top:31px}.menu-page-hero__grid>div p{font-size:13px}.menu-page-index{gap:12px 15px;margin-top:43px}.menu-page-index a{font-size:9px}.menu-page-list{padding-top:48px;padding-bottom:75px}.menu-page-category{display:block;padding:61px 0}.menu-page-category header h2{font-size:58px}.menu-page-category header>p:last-child{margin-top:21px;font-size:12px}.menu-page-category ol{margin-top:33px}.menu-page-category li{min-height:56px}.menu-page-category li strong{font-size:27px}.menu-page-closing{display:block;padding-top:75px;padding-bottom:75px}.menu-page-closing h2{font-size:66px}.menu-page-closing__actions{margin-top:34px}}
`;

export function StructuralStyles() { return <style>{styles}</style>; }
